services:
  database:
    image: mariadb:10.7.3
    environment:
      - MYSQL_ROOT_PASSWORD=Dev
    ports:
      - "3306:3306"

  back:
    image: movies-api:0.0.2
    depends_on:
      - database
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://root:Dev@database:3306/movies_api?charset=utf8mb4
      - MARIADB_DATABASE=movies-api
    ports:
      - "8080:8080"

    volumes:
      - .:/app